### ISSUE TITLE
Examples of GoogleDriveImport with JS Node client?

### ISSUE THREAD

**Issue by impactcolor** [FlatIO/api-client-js#146]
Any examples? I see the ScoreCreation but not using the google drive import.
Thank you in advance!

**Comment by gierschv** [comment]
Hey there,

We have a request sample [in our REST API Docs](https://flat.io/developers/api/reference/#tag/Score/operation/createScore) - Not sure why where is a `source.privacy`, I will check if we need to remove it from that sample:

![Screenshot 2023-08-25 at 08 52 19](https://github.com/FlatIO/api-client-js/assets/396537/4d816564-e888-4e0c-8d47-d5c411177242)

Are you using it with this JS SDK? We haven't updated it for a while, I will need to check what OpenAPI Generator we would use these days.
